fix: yargs update by passing interface to protect the type (#888)
With update on both package:
`yargs` -> `^16.2.0` -> `17.0.0`
`sinon` -> `^10.0.0` -> `^11.0.0`
see #865 

The typescript can't compile on type checks with error msg:
```
error TS2339: Property 'outputDir' does not exist on type '{ [x: string]: unknown; _: (string | number)[]; $0: string; } | Promise<{ [x: string]: unknown; _: (string | number)[]; $0: string; }>'.
  Property 'outputDir' does not exist on type 'Promise<{ [x: string]: unknown; _: (string | number)[]; $0: string; }>'.
  ```
because compiler expect `argv['outputDir'] rather than `argv.outputDir`.
The solution is pass in a interface to protect the type and avoid the typo by passing string in `[]`.

Once it merge, the #880 should pass the test.